### ISSUE TITLE
关于搭建hexo的文件夹

### ISSUE THREAD

**Issue by QAQMiao** [leopardpan/leopardpan.github.io#1]
我看到你博客上说吧搭建hexo的文件夹也上传到了github上，请问是哪个repository？

**Comment by leopardpan** [comment]
这个 repository 就是hexo生成静态页面后的文件夹，你说的hexo文件夹，指的是hexo还没生成静态页面后的原始文件吗？ 那个我没有上传到github，如果你有关于hexo的配置问题的话， 可以直接在这路问。
