### ISSUE TITLE
多说2017年6月1日正式关停服务

### ISSUE THREAD

**Issue by zm47726151** [leopardpan/leopardpan.github.io#14]
多说2017年6月1日正式关停服务，

**Comment by huotaihe** [comment]
同问，后面会怎么处理这块儿功能。

评论功能还是很重要的。

谢谢！

**Comment by leopardpan** [comment]
抱歉，前段时间比较忙，没时间处理，目前使用的是“网易云跟帖”，接下来会做一个评论系统的调研，并发布文章。
