### ISSUE TITLE
搭建hexo的时候出了一些错误

### ISSUE THREAD

**Issue by Verchen** [leopardpan/leopardpan.github.io#2]
![image](https://cloud.githubusercontent.com/assets/14816675/17467344/bbb8683e-5d4f-11e6-91a8-6874d0f4bbdd.png)
不知道是什么原因，请问要怎么解决呢

**Comment by krhomme** [comment]
已经git到了github上 为什么按你说的域名访问 404错误

**Comment by leopardpan** [comment]
@krhomme  我查看了一下你的github账号下没有一个krhomme.github.io 的仓库（krhomme为你的用户名），你需要创建这样一个仓库，然后把你本地的博客push到github上。
