### ISSUE TITLE
搭建hexo的时候遇到的一个问题

### ISSUE THREAD

**Issue by zhoucumt** [leopardpan/leopardpan.github.io#3]
首先，非常感谢你的分享，按照你这篇文章的叙述(http://baixin.io/2015/08/HEXO%E6%90%AD%E5%BB%BA%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2/) 已经在github上成功搭建了一个博客。
但是，有一些不太明白的地方，或者说需要改进的地方。根据你的分享，我在本地建立了一个hexo-blog的目录，也可以正常写博客并发布到github上，然后我把zhoucumt.github.io这个clone到本地，然后我想在里面增加一个READE.ME的文件。
可是，如果我下次再在hexo-blog里面发布一篇博文的时候，会把主干上READE.ME这个文件直接干掉了，这个文件就没了
请问，这个问题怎么解决？非常感谢

**Comment by leopardpan** [comment]
先直接回答你的问题：在你的博客应该是有这样一个目录的  hexo-blog/source/   ，source/ 里面有  _post，你把你的READ.ME文件放在 hexo-blog/source/ 目录下，跟_post同层级，然后把本地博客 使用 hexo d 部署到 github 就可以了。

建议：
你使用hexo搭建的博客，建议你不要直接从github上 clone  zhoucumt.github.io ， 你自己应该会发现，clone下来的项目都是修.html的文件， 你之前写 .md (markdown) 格式 的文章 却不在里面，现在如果你需要在你刚刚clone下来的博客里面添加文章，是无法直添加 .md 格式的文章。
你可以直接在本地操作及的博客即可。

**Comment by zhoucumt** [comment]
我也了解了一下其他人的做法，他们有的是开了一个分支，开一个分支是必须的吗？

**Comment by zhoucumt** [comment]
![image](https://cloud.githubusercontent.com/assets/6021846/18309933/6bdbe182-752e-11e6-8785-1a3ed69c0a56.png)
如图，按照你说的尝试了一下，在和_post平级的目录建立了README.md，里面我只写了"个人博客(开发中。。。)"，可是被生成了html文件
求解？
只能通过分支解决？

**Comment by leopardpan** [comment]
是的，这样做貌似不行，你可以直接在 网页上加README.md文件的， 或者是跟我 现在的一样使用 Jekyll 搭建不可，这样就不用建分支了，也不用担心在多台电脑上不好发博客了

**Comment by fanshengyu** [comment]
怎么移植您的代码到个人服务器上呢？并不想在git上用

**Comment by leopardpan** [comment]
我没在个人服务器上部署过，但原理应该在本地测试服务器差不多，你详细的讲述下你的服务器情况，我可以尝试部署看看

发自我的 iPhone

在 2016年11月20日，00:24，范胜玉 <notifications@github.com<mailto:notifications@github.com>> 写道：


怎么移植您的代码到个人服务器上呢？并不想在git上用

―
