### ISSUE TITLE
tag问题

### ISSUE THREAD

**Issue by wowkingah** [leopardpan/leopardpan.github.io#4]
大神，难得的文章啊。。已星~

有个小问题，我的tag好像没生效，不知道啥情况，特来请教。

cat tags.html
---
layout: page
title: 
header: 根据快速导航到相应的文章
group: navigation
---
{% include JB/setup %}

<ul class="tag_box inline">
  {% assign tags_list = site.tags %}
  {% include JB/tags_list %}
</ul>

<div class = "card">
{% for tag in site.tags %}

  <h3 id="{{ tag[0] }}-ref">{{ tag[0] }}</h3>
  <ul>
    {% assign pages_list = tag[1] %}
    {% include JB/pages_list %}
  </ul>

{% endfor %}
</div>

cat 2016-12-26-my_first_blog.md 
---
layout: post
title: "My first blog for Jekyll~"
date: 2016-12-26
categories: personal
---

Welcome ~
This is my first blog for Jekyll.

tks.

**Comment by leopardpan** [comment]
@wowkingah 

### 明确下问题：“tag好像没生效”，是下面哪种情况？
>* 情况1：tags页面没有生成（没有 /_site/tags/index.html 文件生成）。
>* 情况2：tags页面生成了在（/_site/tags/index.html），没有css样式 。
>* 情况3：tags页面生成了, 启动本地服务时，点击tags里面每天连接，无法进入到具体的文章详情 。

### 解答：
>* 情况1：你需要确认 include 里是否有JB模块，我的模板默认是有的。
>* 情况2：看到你贴的tags.html代码，你已经把我模板里面的HTML标签给删除掉了，所以是没有css样式的。
>* 情况3：如果发生这个情况，你有没有对文件_includes/JB/tags_list有做修改。

如果是以上三种情况，请先还原下我原始模板，按[我的博客教程操作](http://baixin.io/2016/10/jekyll_tutorials1/) 确认是否可以达到你的预期，效果以[我的博客](http://baixin.io/#blog)为准。
如果还是有问题，可能跟你电脑配置环境有关，需要再详细看看你的配置环境。

**Comment by wowkingah** [comment]
多谢回复。
已解决，解决方式：将文章里的categories改为tag。
