### ISSUE TITLE
更改背景格式

### ISSUE THREAD

**Issue by zhaoEJ** [leopardpan/leopardpan.github.io#41]
![default](https://user-images.githubusercontent.com/31759947/39084959-5266df7e-45af-11e8-8456-0f1574eb7bdb.PNG)
您好，非常感谢您做了这么一个炫酷的主题，我非常喜欢。现在我想把背景图片暴露出来，去掉上面这一层颜色，我该修改哪一处的代码？

**Comment by leopardpan** [comment]
在main.css文件里把 panel-cover--overlay 标签下的 background-color 和 background-image 属性都去掉就可以了
