### ISSUE TITLE
文章标题很短的时候,是横向排列的

### ISSUE THREAD

**Issue by huapeng222** [leopardpan/leopardpan.github.io#43]
![image](https://timgsa.baidu.com/timg?image&quality=80%20&size=b10000_10000&sec=1525846639236&di=2f12e53f80b96f806a01b45950c9bde8&imgtype=jpg&src=http%3A%2F%2Fb.hiphotos.baidu.com%2Fimage%2Fpic%2Fitem%2F7a899e510fb30f24cb858bb5c495d143ad4b036c.jpg)

**Comment by leopardpan** [comment]
你在我原来的基础之上做了修改吗？ 我的模板并没有这个问题。
如果你修改的话，注意标签的css样式设置为 float:left ，一行就只显示一个标题了。
