### ISSUE TITLE
阅读次数不显示

### ISSUE THREAD

**Issue by notwhy** [leopardpan/leopardpan.github.io#48]
今天意外的重置了代码，发现文章阅读次数不显示了，打开你的博客baixin.io，发现也是没有显示，是需要更新代码吗？

**Comment by ydzydzydz** [comment]
> 今天意外的重置了代码，发现文章阅读次数不显示了，打开你的博客baixin.io，发现也是没有显示，是需要更新代码吗？

_includes/styles/head.html内


      <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
